############# English navigation ##############


#[[main]]
#name = "Read the docs !"
#pageRef = "/"
#weight = 1


#[[main]]
#weight = 4
#name = "Pages"
#
#[[main]]
#parent = "Pages"
#name = "Blog"
#pageRef = "/blog"
#
#[[main]]
#parent = "Pages"
#name = "Contact"
#pageRef = "/contact"
#
#[[main]]
#parent = "Pages"
#name = "Authors"
#pageRef = "/authors"
#
#[[main]]
#parent = "Pages"
#name = "Categories"
#pageRef = "/categories"
#
#[[main]]
#parent = "Pages"
#name = "404 Page"
#pageRef = "/404"


# footer menu
[[footer]]
name = "Join the waiting list"
pageRef = "join-the-waitling-list"
weight = 2


